// <auto-generated />
using System;
using DripSyndicate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable
using Microsoft.EntityFrameworkCore.Migrations;

namespace DripSyndicate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DripSyndicate.Infrastructure.Persistence.ApplicationDbContext))]
    [Migration("20260601000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DripSyndicate.Domain.Entities.Role", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .HasColumnType("character varying(50)")
                    .HasMaxLength(50);

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("roles", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Email")
                    .HasColumnType("character varying(256)")
                    .HasMaxLength(256);

                b.Property<string>("PasswordHash")
                    .HasColumnType("text");

                b.Property<string>("FullName")
                    .HasColumnType("character varying(120)")
                    .HasMaxLength(120);

                b.Property<string>("Phone")
                    .HasColumnType("text");

                b.Property<bool>("EmailVerified")
                    .HasColumnType("boolean");

                b.Property<string>("Status")
                    .HasColumnType("character varying(20)")
                    .HasMaxLength(20);

                b.Property<string>("PasswordResetTokenHash")
                    .HasColumnType("text");

                b.Property<DateTime>("PasswordResetExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("users", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Category", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .HasColumnType("character varying(120)")
                    .HasMaxLength(120);

                b.Property<string>("Slug")
                    .HasColumnType("text");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<Guid>("ParentId")
                    .HasColumnType("uuid");

                b.Property<string>("ImageUrl")
                    .HasColumnType("text");

                b.Property<int>("Position")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Slug")
                    .IsUnique();
                b.HasIndex("ParentId");

                b.ToTable("categories", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.UserRole", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("user_roles", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<string>("TokenHash")
                    .HasColumnType("text");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("RevokedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ReplacedByTokenHash")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("UserId");
                b.HasIndex("TokenHash");

                b.ToTable("refresh_tokens", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .HasColumnType("character varying(200)")
                    .HasMaxLength(200);

                b.Property<string>("Slug")
                    .HasColumnType("text");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<string>("Currency")
                    .HasColumnType("character varying(3)")
                    .HasMaxLength(3);

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uuid");

                b.Property<bool>("IsFeatured")
                    .HasColumnType("boolean");

                b.Property<DateTime>("PublishedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<double>("RatingAverage")
                    .HasColumnType("double precision");

                b.Property<int>("RatingCount")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Slug")
                    .IsUnique();
                b.HasIndex("Status", "PublishedAt");
                b.HasIndex("CategoryId");

                b.ToTable("products", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.ProductVariant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b.Property<string>("Sku")
                    .HasColumnType("character varying(64)")
                    .HasMaxLength(64);

                b.Property<string>("Size")
                    .HasColumnType("text");

                b.Property<string>("Color")
                    .HasColumnType("text");

                b.Property<decimal>("Price")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<int>("StockOnHand")
                    .HasColumnType("integer");

                b.Property<int>("StockReserved")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Sku")
                    .IsUnique();
                b.HasIndex("ProductId");

                b.ToTable("product_variants", t =>
                {
                    t.HasCheckConstraint("ck_no_oversell", "\"StockOnHand\" - \"StockReserved\" >= 0");
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.ProductImage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b.Property<string>("Url")
                    .HasColumnType("text");

                b.Property<string>("ThumbnailUrl")
                    .HasColumnType("text");

                b.Property<int>("Position")
                    .HasColumnType("integer");

                b.Property<string>("Alt")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("ProductId");

                b.ToTable("product_images", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.CartItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("ProductVariantId")
                    .HasColumnType("uuid");

                b.Property<int>("Quantity")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("UserId", "ProductVariantId")
                    .IsUnique();
                b.HasIndex("ProductVariantId");

                b.ToTable("cart_items", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.WishlistItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("UserId", "ProductId")
                    .IsUnique();
                b.HasIndex("ProductId");

                b.ToTable("wishlist_items", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Order", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Number")
                    .HasColumnType("text");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<decimal>("Subtotal")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<decimal>("Discount")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<decimal>("Shipping")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<decimal>("Tax")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<decimal>("Total")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<string>("Currency")
                    .HasColumnType("character varying(3)")
                    .HasMaxLength(3);

                b.Property<string>("ShipFullName")
                    .HasColumnType("text");

                b.Property<string>("ShipLine1")
                    .HasColumnType("text");

                b.Property<string>("ShipLine2")
                    .HasColumnType("text");

                b.Property<string>("ShipCity")
                    .HasColumnType("text");

                b.Property<string>("ShipPostalCode")
                    .HasColumnType("text");

                b.Property<string>("ShipCountry")
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Number")
                    .IsUnique();
                b.HasIndex("UserId", "CreatedAt");

                b.ToTable("orders", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.OrderItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uuid");

                b.Property<Guid>("ProductVariantId")
                    .HasColumnType("uuid");

                b.Property<string>("NameSnapshot")
                    .HasColumnType("text");

                b.Property<string>("SkuSnapshot")
                    .HasColumnType("text");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<int>("Quantity")
                    .HasColumnType("integer");

                b.Property<decimal>("LineTotal")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("order_items", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Payment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uuid");

                b.Property<string>("Provider")
                    .HasColumnType("text");

                b.Property<string>("IntentId")
                    .HasColumnType("text");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric(12,2)")
                    .HasPrecision(12, 2);

                b.Property<string>("Currency")
                    .HasColumnType("character varying(3)")
                    .HasMaxLength(3);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("OrderId")
                    .IsUnique();
                b.HasIndex("Provider", "IntentId");

                b.ToTable("payments", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Review", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<int>("Rating")
                    .HasColumnType("integer");

                b.Property<string>("Title")
                    .HasColumnType("text");

                b.Property<string>("Body")
                    .HasColumnType("text");

                b.Property<bool>("IsApproved")
                    .HasColumnType("boolean");

                b.Property<bool>("VerifiedPurchase")
                    .HasColumnType("boolean");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("UserId", "ProductId")
                    .IsUnique();
                b.HasIndex("ProductId", "CreatedAt");

                b.ToTable("reviews", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.ContactMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .HasColumnType("text");

                b.Property<string>("Subject")
                    .HasColumnType("text");

                b.Property<string>("Message")
                    .HasColumnType("text");

                b.Property<bool>("IsHandled")
                    .HasColumnType("boolean");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");


                b.ToTable("contact_messages", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.MediaAsset", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Bucket")
                    .HasColumnType("text");

                b.Property<string>("Path")
                    .HasColumnType("text");

                b.Property<string>("Url")
                    .HasColumnType("text");

                b.Property<string>("ThumbnailUrl")
                    .HasColumnType("text");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.Property<int>("Scope")
                    .HasColumnType("integer");

                b.Property<long>("SizeBytes")
                    .HasColumnType("bigint");

                b.Property<int>("Width")
                    .HasColumnType("integer");

                b.Property<int>("Height")
                    .HasColumnType("integer");

                b.Property<string>("ContentType")
                    .HasColumnType("text");

                b.Property<string>("Alt")
                    .HasColumnType("text");

                b.Property<Guid>("OwnerEntityId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Path");

                b.ToTable("media_assets", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Banner", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Title")
                    .HasColumnType("text");

                b.Property<string>("Subtitle")
                    .HasColumnType("text");

                b.Property<string>("ImageUrl")
                    .HasColumnType("text");

                b.Property<string>("LinkUrl")
                    .HasColumnType("text");

                b.Property<int>("Position")
                    .HasColumnType("integer");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<DateTime>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("EndsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");


                b.ToTable("banners", t =>
                {
                });
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.PromoVideo", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Title")
                    .HasColumnType("text");

                b.Property<string>("VideoUrl")
                    .HasColumnType("text");

                b.Property<string>("PosterUrl")
                    .HasColumnType("text");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<int>("Position")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");


                b.ToTable("promo_videos", t =>
                {
                });
            });

            modelBuilder.Entity("DripSyndicate.Domain.Entities.Category", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Category", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.UserRole", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.UserRole", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Role", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Product", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Category", null)
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.ProductVariant", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Product", null)
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.ProductImage", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Product", null)
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.CartItem", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.CartItem", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.ProductVariant", null)
                    .WithMany()
                    .HasForeignKey("ProductVariantId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.WishlistItem", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.WishlistItem", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Product", null)
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Order", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.SetNull);
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.OrderItem", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Payment", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Order", null)
                    .WithMany()
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Review", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.Product", null)
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("DripSyndicate.Domain.Entities.Review", b =>
            {
                b.HasOne("DripSyndicate.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
